# Generated by Django 3.2.6 on 2021-08-20 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message_recieved', models.TextField()),
                ('date_recieved', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
